@extends('layouts.app')
@section('robots', 'noindex,follow')
@section('meta_title', __('cart').' | C.E.S. Container')
@section('content')
<section class="container py-4 py-lg-5">
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><span class="text-success fw-bold text-uppercase small">C.E.S. Container</span><h1 class="h2 mb-1">Votre panier</h1><p class="text-muted mb-0">Vérifiez vos articles et contactez notre équipe si besoin.</p></div><a href="{{ route('shop') }}" class="btn btn-outline-success"><i class="bi bi-arrow-left me-1"></i>Continuer mes achats</a></div>
    <div class="row g-4 align-items-start">
        <div class="col-lg-8">
            @if($items->isEmpty())
                <div class="card border-0 shadow-sm"><div class="card-body text-center py-5"><i class="bi bi-cart3 display-5 text-success"></i><h2 class="h4 mt-3">Votre panier est vide</h2><p class="text-muted">Découvrez nos conteneurs disponibles dans la boutique.</p><a class="btn btn-success" href="{{ route('shop') }}">Voir la boutique</a></div></div>
            @else
                <div class="card border-0 shadow-sm"><form id="cart-update" method="post" action="{{ route('cart.update') }}">@csrf<div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Produit</th><th>Type</th><th>Prix unitaire HT</th><th>Quantité</th><th>Total HT</th><th></th></tr></thead><tbody>@foreach($items as $item)<tr><td><strong>{{ $item['container']->reference }}</strong><div class="small text-muted">{{ $item['container']->category->nom ?? '' }}</div></td><td>{{ $item['type']==='location'?'Location':'Achat' }}</td><td>{{ number_format($item['unit_price'],2,',',' ') }} €</td><td><input class="form-control" type="number" name="items[{{ $item['container']->id }}][quantity]" value="{{ $item['quantity'] }}" min="1" max="100" style="width:88px" aria-label="Quantité pour {{ $item['container']->reference }}"></td><td class="fw-bold">{{ number_format($item['total'],2,',',' ') }} €</td><td><button class="btn btn-sm btn-outline-danger" type="submit" form="cart-remove-{{ $item['container']->id }}" aria-label="Supprimer {{ $item['container']->reference }}"><i class="bi bi-trash"></i></button></td></tr>@endforeach</tbody></table></div></form><div class="card-body d-flex justify-content-between align-items-center gap-3"><span class="text-muted small">Les frais éventuels seront confirmés avec votre commande.</span><button class="btn btn-outline-success" type="submit" form="cart-update"><i class="bi bi-arrow-repeat me-1"></i>Mettre à jour</button></div>@foreach($items as $item)<form id="cart-remove-{{ $item['container']->id }}" method="post" action="{{ route('cart.remove',$item['container']->id) }}" hidden>@csrf @method('DELETE')</form>@endforeach</div>
                <div class="card border-0 shadow-sm mt-4"><div class="card-body"><div class="d-flex justify-content-between mb-2"><span>Sous-total HT</span><strong>{{ number_format($totals['ht'],2,',',' ') }} €</strong></div><div class="d-flex justify-content-between mb-3"><span>TVA ({{ $totals['vat_rate'] }}%)</span><strong>{{ number_format($totals['tva'],2,',',' ') }} €</strong></div><div class="d-flex justify-content-between border-top pt-3 fs-4"><span>Total TTC</span><strong>{{ number_format($totals['ttc'],2,',',' ') }} €</strong></div><a href="{{ route('checkout.form') }}" class="btn btn-success w-100 mt-3">Passer la commande <i class="bi bi-arrow-right ms-1"></i></a></div></div>
            @endif
        </div>
        <aside class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white py-3"><h2 class="h5 mb-0"><i class="bi bi-headset text-success me-2"></i>Besoin d’aide ?</h2></div><div class="card-body"><p class="text-muted">Contactez directement {{ $company['name'] }} pour toute question sur votre sélection.</p>@if($company['phone'])<a class="contact-detail" href="tel:{{ preg_replace('/[^0-9+]/','',$company['phone']) }}"><i class="bi bi-telephone"></i><span>{{ $company['phone'] }}</span></a>@endif @if($company['email'])<a class="contact-detail" href="mailto:{{ $company['email'] }}"><i class="bi bi-envelope"></i><span>{{ $company['email'] }}</span></a>@endif @if($company['address'])<div class="contact-detail"><i class="bi bi-geo-alt"></i><span>{!! nl2br(e($company['address'])) !!}</span></div><a class="btn btn-sm btn-outline-success mt-2" href="https://www.google.com/maps/search/?api=1&query={{ urlencode($company['address']) }}" target="_blank" rel="noopener"><i class="bi bi-map me-1"></i>Voir l’adresse sur la carte</a>@endif</div></div></aside>
    </div>
</section>
@endsection
