@extends('admin.layouts.app')
@section('content')
<div class="admin-page-head"><div><span class="admin-kicker">Médiathèque</span><h1>Galerie des conteneurs</h1><p>Consultez les photos du catalogue et ouvrez une fiche pour les gérer.</p></div></div>
<div class="admin-gallery-toolbar card border-0 shadow-sm mb-4"><div><strong>{{ number_format($total) }}</strong><span>conteneur(s) avec image principale</span></div><form method="get" class="row g-2 align-items-end"><div class="col-12 col-md"><label for="gallery-search" class="form-label small fw-bold">Recherche</label><input id="gallery-search" name="search" class="form-control" value="{{ request('search') }}" placeholder="Référence ou type"></div><div class="col-12 col-md"><label for="gallery-category" class="form-label small fw-bold">Catégorie</label><select id="gallery-category" name="categorie" class="form-select"><option value="">Toutes les catégories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('categorie')==$category->id)>{{ $category->nom }}</option>@endforeach</select></div><div class="col-auto"><button class="btn btn-success"><i class="bi bi-funnel"></i> Filtrer</button></div><div class="col-auto"><a href="{{ route('admin.gallery') }}" class="btn btn-outline-secondary" title="Réinitialiser"><i class="bi bi-arrow-counterclockwise"></i></a></div></form></div>
<div class="admin-gallery-grid">@forelse($items as $item)
    <article class="admin-gallery-item"><button type="button" class="admin-gallery-photo" data-bs-toggle="modal" data-bs-target="#galleryModal" data-image="{{ asset($item->image_principale) }}" data-reference="{{ $item->reference }}" data-category="{{ $item->category->nom ?? 'Sans catégorie' }}" data-type="{{ ucfirst(str_replace('_',' ',$item->type_conteneur ?? '')) }}" aria-label="Agrandir l’image de {{ $item->reference }}"><img src="{{ asset($item->image_principale) }}" alt="{{ $item->reference }}" loading="lazy"><span><i class="bi bi-zoom-in"></i></span></button><div class="admin-gallery-caption"><div><strong>{{ $item->reference }}</strong><small>{{ $item->category->nom ?? 'Sans catégorie' }} · {{ ucfirst(str_replace('_',' ',$item->type_conteneur ?? '')) }}</small></div><a class="btn btn-sm btn-outline-success" href="{{ route('admin.conteneurs.edit',$item) }}" title="Modifier les images"><i class="bi bi-pencil-square"></i></a></div></article>
@empty<div class="admin-gallery-empty"><i class="bi bi-images"></i><strong>Aucune image ne correspond à ces critères.</strong></div>@endforelse</div>
@if($items->hasPages())<nav class="admin-pagination" aria-label="Pagination de la galerie"><div class="admin-pagination-summary">Affichage de <strong>{{ $items->firstItem() }}–{{ $items->lastItem() }}</strong> sur <strong>{{ $items->total() }}</strong></div><div class="admin-pagination-links">@if($items->onFirstPage())<span class="page-control disabled"><i class="bi bi-chevron-left"></i> Précédent</span>@else<a class="page-control" href="{{ $items->previousPageUrl() }}"><i class="bi bi-chevron-left"></i> Précédent</a>@endif @foreach($items->getUrlRange(max(1,$items->currentPage()-2),min($items->lastPage(),$items->currentPage()+2)) as $page=>$url)<a class="page-number {{ $page===$items->currentPage()?'active':'' }}" href="{{ $url }}" @if($page===$items->currentPage()) aria-current="page" @endif>{{ $page }}</a>@endforeach @if($items->hasMorePages())<a class="page-control" href="{{ $items->nextPageUrl() }}">Suivant <i class="bi bi-chevron-right"></i></a>@else<span class="page-control disabled">Suivant <i class="bi bi-chevron-right"></i></span>@endif</div></nav>@endif
<div class="modal fade" id="galleryModal" tabindex="-1" aria-labelledby="galleryModalTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-xl"><div class="modal-content admin-gallery-modal"><div class="modal-header"><div><h2 class="modal-title h5 mb-0" id="galleryModalTitle"></h2><div class="small text-muted" id="galleryModalDetails"></div></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button></div><div class="modal-body"><img id="galleryModalImage" src="" alt="" class="img-fluid"></div><div class="modal-footer"><a id="galleryEditLink" class="btn btn-success" href="#"><i class="bi bi-pencil-square me-1"></i>Modifier le conteneur</a><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Fermer</button></div></div></div></div>
@push('scripts')<script>document.querySelectorAll('.admin-gallery-photo').forEach(button=>button.addEventListener('click',()=>{const img=document.querySelector('#galleryModalImage');img.src=button.dataset.image;img.alt=button.dataset.reference;document.querySelector('#galleryModalTitle').textContent=button.dataset.reference;document.querySelector('#galleryModalDetails').textContent=[button.dataset.category,button.dataset.type].filter(Boolean).join(' · ');document.querySelector('#galleryEditLink').href=button.closest('.admin-gallery-item').querySelector('.admin-gallery-caption a').href}));</script>@endpush
@endsection
