@extends('admin.layouts.app')
@section('content')
<div class="admin-page-head"><div><span class="admin-kicker">Catalogue</span><h1>Gestion des conteneurs</h1><p>Recherchez, filtrez et gérez les stocks depuis un seul espace.</p></div><a href="{{ route('admin.conteneurs.create') }}" class="btn btn-success"><i class="bi bi-plus-lg"></i> Nouveau conteneur</a></div>
<div class="admin-stat-grid mb-4">@foreach([['Total',$stats['total'],'bi-box-seam','text-success'],['Disponibles',$stats['disponibles'],'bi-check2-circle','text-primary'],['Stock à contrôler',$stats['alerte'],'bi-exclamation-triangle','text-warning'],['Maintenance',$stats['maintenance'],'bi-wrench-adjustable','text-danger']] as [$label,$value,$icon,$color])<div class="admin-stat-card"><i class="bi {{ $icon }} {{ $color }}"></i><div><small>{{ $label }}</small><strong>{{ $value }}</strong></div></div>@endforeach</div>
<form method="get" class="card border-0 shadow-sm p-3 mb-4 admin-filter-bar"><div class="row g-2 align-items-end"><div class="col-12 col-lg-5"><label class="form-label small fw-bold">Recherche</label><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input name="search" value="{{ request('search') }}" class="form-control" placeholder="Référence, type ou état"></div></div><div class="col-12 col-md-4 col-lg-3"><label class="form-label small fw-bold">Catégorie</label><select name="categorie" class="form-select"><option value="">Toutes les catégories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('categorie') == $category->id)>{{ $category->nom }}</option>@endforeach</select></div><div class="col-12 col-md-4 col-lg-2"><label class="form-label small fw-bold">Statut</label><select name="statut" class="form-select"><option value="">Tous</option>@foreach(['disponible','vendu','loue','maintenance'] as $status)<option value="{{ $status }}" @selected(request('statut') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-12 col-md-4 col-lg-2 d-flex gap-2"><button class="btn btn-success flex-grow-1"><i class="bi bi-funnel"></i> Filtrer</button><a class="btn btn-outline-secondary" href="{{ route('admin.conteneurs.index') }}" title="Réinitialiser"><i class="bi bi-arrow-counterclockwise"></i></a></div></div></form>
<form method="post" action="{{ route('admin.conteneurs.bulk-destroy') }}" class="card border-0 shadow-sm" onsubmit="return confirm('Supprimer les conteneurs sélectionnés ?')">@csrf<div class="card-header d-flex justify-content-between align-items-center gap-2"><span><strong>{{ $items->total() }}</strong> résultat(s)</span><button class="btn btn-sm btn-outline-danger" id="bulkDelete" disabled><i class="bi bi-trash"></i> Supprimer la sélection</button></div><div class="table-responsive admin-table-wrap"><table class="table align-middle mb-0"><thead><tr><th><input type="checkbox" class="form-check-input" id="selectAll" aria-label="Tout sélectionner"></th><th>Conteneur</th><th>Catégorie</th><th>Stock</th><th>Vente</th><th>Statut</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($items as $item)<tr><td><input type="checkbox" class="form-check-input item-check" name="selected_ids[]" value="{{ $item->id }}"></td><td><div class="container-cell"><div class="container-thumb">@if($item->image_principale)<img src="{{ asset($item->image_principale) }}" alt="Image {{ $item->reference }}" loading="lazy">@else<i class="bi bi-box-seam"></i>@endif</div><div><strong>{{ $item->reference }}</strong><small>{{ $item->type_conteneur ?: 'Type non précisé' }}</small></div></div></td><td>{{ $item->category->nom ?? '—' }}</td><td><span class="stock-pill {{ $item->quantite_stock <= ($item->quantite_min_alerte ?? 0) ? 'is-low' : '' }}">{{ $item->quantite_stock }}</span></td><td class="fw-bold">{{ number_format((float)$item->prix_vente,2,',',' ') }} €</td><td><span class="status-pill status-{{ $item->statut }}">{{ ucfirst($item->statut) }}</span></td><td class="text-end"><div class="btn-group"><a href="{{ route('admin.conteneurs.edit',$item) }}" class="btn btn-sm btn-outline-success" title="Modifier"><i class="bi bi-pencil-square"></i></a><button type="button" class="btn btn-sm btn-outline-danger" title="Supprimer" onclick="document.getElementById('delete-{{ $item->id }}').submit()"><i class="bi bi-trash"></i></button></div></td></tr>@empty<tr><td colspan="7" class="text-center py-5 text-muted">Aucun conteneur ne correspond à ces critères.</td></tr>@endforelse</tbody></table></div></form>
@if($items->hasPages())
<nav class="admin-pagination" aria-label="Pagination des conteneurs">
    <div class="admin-pagination-summary">Affichage de <strong>{{ $items->firstItem() }}–{{ $items->lastItem() }}</strong> sur <strong>{{ $items->total() }}</strong></div>
    <div class="admin-pagination-links">
        @if($items->onFirstPage())<span class="page-control disabled"><i class="bi bi-chevron-left"></i><span>Précédent</span></span>@else<a class="page-control" href="{{ $items->previousPageUrl() }}"><i class="bi bi-chevron-left"></i><span>Précédent</span></a>@endif
        @foreach($items->getUrlRange(max(1,$items->currentPage()-2),min($items->lastPage(),$items->currentPage()+2)) as $page=>$url)
            <a class="page-number {{ $page===$items->currentPage()?'active':'' }}" href="{{ $url }}" @if($page===$items->currentPage()) aria-current="page" @endif>{{ $page }}</a>
        @endforeach
        @if($items->hasMorePages())<a class="page-control" href="{{ $items->nextPageUrl() }}"><span>Suivant</span><i class="bi bi-chevron-right"></i></a>@else<span class="page-control disabled"><span>Suivant</span><i class="bi bi-chevron-right"></i></span>@endif
    </div>
</nav>
@endif
@foreach($items as $item)<form id="delete-{{ $item->id }}" method="post" action="{{ route('admin.conteneurs.destroy',$item) }}" class="d-none">@csrf @method('DELETE')</form>@endforeach
<script>document.addEventListener('DOMContentLoaded',()=>{const all=document.querySelector('#selectAll'),boxes=[...document.querySelectorAll('.item-check')],btn=document.querySelector('#bulkDelete');const sync=()=>{btn.disabled=!boxes.some(x=>x.checked);all.checked=boxes.length>0&&boxes.every(x=>x.checked)};all?.addEventListener('change',()=>{boxes.forEach(x=>x.checked=all.checked);sync()});boxes.forEach(x=>x.addEventListener('change',sync))});</script>
@endsection
